pip install pandas

In [6]:
import pandas as pd
import numpy as np

**Series**

In [ ]:
s1 = pd.Series([24,1,5,66,88,99])
s1

0    24
1     1
2     5
3    66
4    88
5    99
dtype: int64

In [ ]:
s2 = pd.Series([24,1,5,66,88,99],index = {'pavan','gopi','hulk','gouse','sam','ram'})
s2

pavan    24
ram       1
hulk      5
sam      66
gopi     88
gouse    99
dtype: int64

In [ ]:
s1

0    24
1     1
2     5
3    66
4    88
5    99
dtype: int64

In [ ]:
s3 = pd.Series([24,1,5,66,88,99],index={'pavan','gopi','hulk','gouse','sam','ram'},dtype = float)
s2

pavan    24.0
ram       1.0
hulk      5.0
sam      66.0
gopi     88.0
gouse    99.0
dtype: float64

In [ ]:
s3['pavan']

np.float64(24.0)

In [ ]:
s3[0]

/tmp/ipython-input-397937684.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s3[0]

np.float64(24.0)

In [ ]:
s3["hulk"]

np.float64(5.0)

In [ ]:
students = pd.Series(['pavan','gopi','hulk','gouse','sam','ram'],index = ["I","II","III","IV","V","VI"])
students

I      pavan
II      gopi
III     hulk
IV     gouse
V        sam
VI       ram
dtype: object

In [ ]:
students["I"]

'pavan'

In [ ]:
students["VI"]

'ram'

In [ ]:
students[3]

/tmp/ipython-input-1158474101.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  students[3]

'gouse'

Creation of series using Dictionary

In [ ]:
s4 = pd.Series({'a': 1, 'v' : 2, 'c': 3,'d' : 4})
s4

a    1
v    2
c    3
d    4
dtype: int64

**Dataframe**

In [ ]:
s1 = pd.DataFrame([24,1,5,66,88,99])
s1

    0
0  24
1   1
2   5
3  66
4  88
5  99

In [ ]:
d2 = pd.DataFrame([10,20,30],[40,50,60])
d2

     0
40  10
50  20
60  30

In [ ]:
d2 = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]])
d2

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [ ]:
students

I      pavan
II      gopi
III     hulk
IV     gouse
V        sam
VI       ram
dtype: object

In [ ]:
# convert to series to DataFrame
d2 = pd.DataFrame(students)
d2

         0
I    pavan
II    gopi
III   hulk
IV   gouse
V      sam
VI     ram

In [ ]:
d3 = pd.DataFrame([[70,80,90],[40,50,60],[10,20,30]],columns = ["maths","phy","chemstry"],index = ["pavan","gopi","Hulk"])
d3

       maths  phy  chemstry
pavan     70   80        90
gopi      40   50        60
Hulk      10   20        30

In [ ]:

d2
#students

         0
I    pavan
II    gopi
III   hulk
IV   gouse
V      sam
VI     ram

In [ ]:
dictionary = [{'pa1':1,'gop':2,'bro':4},{'pa1':55,'bro':45,'didi':00}]
dictionary

[{'pa1': 1, 'gop': 2, 'bro': 4}, {'pa1': 55, 'bro': 45, 'didi': 0}]

In [ ]:
dictionary = [{'pa1':1,'gop':2,'bro':4},{'pa1':55,'bro':45,'didi':00}]
pd.DataFrame(dictionary,index = ['x','y'],dtype = float)

    pa1  gop   bro  didi
x   1.0  2.0   4.0   NaN
y  55.0  NaN  45.0   0.0

In [ ]:
dictionary = [{'pa1':1,'gop':2,'bro':4},{'pa1':55,'bro':45,'didi':00}]
pd.DataFrame(dictionary,index = ['x','y'],dtype = int)

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer

**DataFrame operations**

In [ ]:
marks = pd.DataFrame([[70,80,90],[40,50,60],[10,20,30]],columns = ["maths","phy","chemstry"],index = ["pavan","gopi","Hulk"])
marks

       maths  phy  chemstry
pavan     70   80        90
gopi      40   50        60
Hulk      10   20        30

In [ ]:
marks['chemstry']

pavan    90
gopi     60
Hulk     30
Name: chemstry, dtype: int64

In [ ]:
marks['phy']

pavan    80
gopi     50
Hulk     20
Name: phy, dtype: int64

In [ ]:
marks['maths']['pavan']

np.int64(70)

In [ ]:
marks['maths']['gopi']

np.int64(40)

In [ ]:
marks['Total'] = marks['maths']+marks['phy']+marks['chemstry']
marks

       maths  phy  chemstry  Total
pavan     70   80        90    240
gopi      40   50        60    150
Hulk      10   20        30     60

In [ ]:
marks["percantage"] = (marks['Total']/300)*100
marks

       maths  phy  chemstry  Total  percantage
pavan     70   80        90    240        80.0
gopi      40   50        60    150        50.0
Hulk      10   20        30     60        20.0

In [ ]:
marks.percantage

pavan    80.0
gopi     50.0
Hulk     20.0
Name: percantage, dtype: float64

In [ ]:
marks.Total

pavan    240
gopi     150
Hulk      60
Name: Total, dtype: int64

In [ ]:
pop = marks.pop('phy')
pop

pavan    80
gopi     50
Hulk     20
Name: phy, dtype: int64

In [ ]:
marks

       maths  phy  chemstry  Total  percantage
pavan     70   80        90    240        80.0
gopi      40   50        60    150        50.0
Hulk      10   20        30     60        20.0

In [ ]:
marks.insert(3,"Qc",[99,97,95])
marks

       maths  phy  chemstry  Qc  Total  percantage
pavan     70   80        90  99    240        80.0
gopi      40   50        60  97    150        50.0
Hulk      10   20        30  95     60        20.0

In [ ]:
d4 = pd.DataFrame({'ram':np.random.randint(1,10,size = (30)),'pa1':np.random.randint(2,10,size = (30)),'Hulk':np.random.randint(3,10,size = (30))})
d4

    ram  pa1  Hulk
0     2    4     7
1     4    8     3
2     8    9     9
3     7    8     4
4     1    5     5
5     9    9     3
6     4    9     7
7     3    2     5
8     1    6     6
9     6    2     3
10    5    5     7
11    8    6     5
12    5    9     4
13    8    4     3
14    4    2     6
15    4    8     7
16    4    9     4
17    5    8     3
18    6    8     6
19    2    3     7
20    5    6     6
21    7    6     5
22    9    4     6
23    6    7     5
24    4    2     9
25    8    8     5
26    4    3     5
27    8    7     3
28    3    4     5
29    9    5     5

In [ ]:
d4.head()

   ram  pa1  Hulk
0    2    4     7
1    4    8     3
2    8    9     9
3    7    8     4
4    1    5     5

In [ ]:
d4.head(10)

   ram  pa1  Hulk
0    2    4     7
1    4    8     3
2    8    9     9
3    7    8     4
4    1    5     5
5    9    9     3
6    4    9     7
7    3    2     5
8    1    6     6
9    6    2     3

In [ ]:
d4.tail()

    ram  pa1  Hulk
25    8    8     5
26    4    3     5
27    8    7     3
28    3    4     5
29    9    5     5

In [ ]:
d4.tail(5)

    ram  pa1  Hulk
25    8    8     5
26    4    3     5
27    8    7     3
28    3    4     5
29    9    5     5

In [ ]:
d4.loc[10,"pa1"]

np.int64(5)

In [ ]:
d4.loc[11,"ram"]

np.int64(8)

In [ ]:
d4.loc[10:19,'pa1']

10    5
11    6
12    9
13    4
14    2
15    8
16    9
17    8
18    8
19    3
Name: pa1, dtype: int64

In [ ]:
d4.loc[16:9,"pa1"]

Series([], Name: pa1, dtype: int64)

In [ ]:
d4.loc[10:16,["pa1","ram"]]

    pa1  ram
10    5    5
11    6    8
12    9    5
13    4    8
14    2    4
15    8    4
16    9    4

In [ ]:
d4.loc[10:16,["Hulk","ram"]]

    Hulk  ram
10     7    5
11     5    8
12     4    5
13     3    8
14     6    4
15     7    4
16     4    4

In [ ]:
d4.tail(10)

    ram  pa1  Hulk
20    5    6     6
21    7    6     5
22    9    4     6
23    6    7     5
24    4    2     9
25    8    8     5
26    4    3     5
27    8    7     3
28    3    4     5
29    9    5     5

In [ ]:
d4.iloc[4,1]  # index = 4 and coluhms = 1 as 2nd columns

np.int64(5)

In [ ]:
d4.iloc[4:9,[0,2]]

   ram  Hulk
4    1     5
5    9     3
6    4     7
7    3     5
8    1     6

In [ ]:
d4.iloc[[1,5,6,9,8,7,4,5,6,4,2,3,3,3]]

   ram  pa1  Hulk
1    4    8     3
5    9    9     3
6    4    9     7
9    6    2     3
8    1    6     6
7    3    2     5
4    1    5     5
5    9    9     3
6    4    9     7
4    1    5     5
2    8    9     9
3    7    8     4
3    7    8     4
3    7    8     4

In [ ]:
d4.pa1

0     4
1     8
2     9
3     8
4     5
5     9
6     9
7     2
8     6
9     2
10    5
11    6
12    9
13    4
14    2
15    8
16    9
17    8
18    8
19    3
20    6
21    6
22    4
23    7
24    2
25    8
26    3
27    7
28    4
29    5
Name: pa1, dtype: int64

In [ ]:
d4["pa1"]

0     4
1     8
2     9
3     8
4     5
5     9
6     9
7     2
8     6
9     2
10    5
11    6
12    9
13    4
14    2
15    8
16    9
17    8
18    8
19    3
20    6
21    6
22    4
23    7
24    2
25    8
26    3
27    7
28    4
29    5
Name: pa1, dtype: int64

In [ ]:
d4["Total"] = d4["pa1"]+ d4["Hulk"]+ d4["ram"]
d4

    ram  pa1  Hulk  Total
0     2    4     7     13
1     4    8     3     15
2     8    9     9     26
3     7    8     4     19
4     1    5     5     11
5     9    9     3     21
6     4    9     7     20
7     3    2     5     10
8     1    6     6     13
9     6    2     3     11
10    5    5     7     17
11    8    6     5     19
12    5    9     4     18
13    8    4     3     15
14    4    2     6     12
15    4    8     7     19
16    4    9     4     17
17    5    8     3     16
18    6    8     6     20
19    2    3     7     12
20    5    6     6     17
21    7    6     5     18
22    9    4     6     19
23    6    7     5     18
24    4    2     9     15
25    8    8     5     21
26    4    3     5     12
27    8    7     3     18
28    3    4     5     12
29    9    5     5     19

In [1]:
employees = [
    ['rk', 100, 19000],
    ['js', 101, 22000],
    ['am', 102, 18500],
    ['pt', 103, 25000],
    ['ks', 104, 21000],
    ['rv', 105, 20000],
    ['sl', 106, 23000],
    ['mj', 107, 19500],
    ['dp', 108, 24000],
     ['cl', 109, 20500]
  ]
employees

[['rk', 100, 19000],
 ['js', 101, 22000],
 ['am', 102, 18500],
 ['pt', 103, 25000],
 ['ks', 104, 21000],
 ['rv', 105, 20000],
 ['sl', 106, 23000],
 ['mj', 107, 19500],
 ['dp', 108, 24000],
 ['cl', 109, 20500]]

In [7]:
p1 = pd.DataFrame(employees,columns =["name","idno","salary"])
p1

  name  idno  salary
0   rk   100   19000
1   js   101   22000
2   am   102   18500
3   pt   103   25000
4   ks   104   21000
5   rv   105   20000
6   sl   106   23000
7   mj   107   19500
8   dp   108   24000
9   cl   109   20500

In [11]:
p1[p1.salary>=25000]

  name  idno  salary
3   pt   103   25000

In [10]:
p1[p1.salary<=20000]

  name  idno  salary
0   rk   100   19000
2   am   102   18500
5   rv   105   20000
7   mj   107   19500

In [24]:
new_row = pd.DataFrame([{"name":"pavan", "idno":np.nan,"salary":56500}])
p1 = pd.concat([p1, new_row], ignore_index=True)
p1

     name   idno  salary
0      rk  100.0   19000
1      js  101.0   22000
2      am  102.0   18500
3      pt  103.0   25000
4      ks  104.0   21000
5      rv  105.0   20000
6      sl  106.0   23000
7      mj  107.0   19500
8      dp  108.0   24000
9      cl  109.0   20500
10  pavan  100.0   35000
11  pavan    NaN   35000
12  pavan    NaN   56500

In [25]:
p1.isnull()

     name   idno  salary
0   False  False   False
1   False  False   False
2   False  False   False
3   False  False   False
4   False  False   False
5   False  False   False
6   False  False   False
7   False  False   False
8   False  False   False
9   False  False   False
10  False  False   False
11  False   True   False
12  False   True   False

In [26]:
p1.isnull().sum()

name      0
idno      2
salary    0
dtype: int64

In [29]:
samba = p1.dropna()

In [30]:
samba

     name   idno  salary
0      rk  100.0   19000
1      js  101.0   22000
2      am  102.0   18500
3      pt  103.0   25000
4      ks  104.0   21000
5      rv  105.0   20000
6      sl  106.0   23000
7      mj  107.0   19500
8      dp  108.0   24000
9      cl  109.0   20500
10  pavan  100.0   35000

** groupby**

In [31]:
df = pd.DataFrame({'Animal':['falcon','falcon','parrot','parrot'],'max_speed':[600,500,900,400]})
df

   Animal  max_speed
0  falcon        600
1  falcon        500
2  parrot        900
3  parrot        400

In [35]:
df.groupby(['Animal']).mean()

        max_speed
Animal
falcon      550.0
parrot      650.0

In [38]:
df.groupby(["Animal"]).sum()

        max_speed
Animal
falcon       1100
parrot       1300

In [42]:
df_csv = pd.read_csv("/student-data.csv")
df_csv.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,passed
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,no,no,4,3,4,1,1,3,6,no
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,yes,no,5,3,3,1,1,3,4,no
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,yes,no,4,3,2,2,3,3,10,yes
3,GP,F,15,U,GT3,T,4,2,health,services,...,yes,yes,3,2,2,1,1,5,2,yes
4,GP,F,16,U,GT3,T,3,3,other,other,...,no,no,4,3,2,1,2,5,4,yes

In [43]:
df_csv.tail()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,passed
390,MS,M,20,U,LE3,A,2,2,services,services,...,no,no,5,5,4,4,5,4,11,no
391,MS,M,17,U,LE3,T,3,1,services,services,...,yes,no,2,4,5,3,4,2,3,yes
392,MS,M,21,R,GT3,T,1,1,other,other,...,no,no,5,5,3,3,3,3,3,no
393,MS,M,18,R,LE3,T,3,2,services,other,...,yes,no,4,4,1,3,4,5,0,yes
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,yes,no,3,2,3,3,3,5,5,no

In [44]:
df_csv.isnull()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,passed
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
391,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
392,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
393,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
394,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [45]:
df_csv.isnull().sum()

school        0
sex           0
age           0
address       0
famsize       0
Pstatus       0
Medu          0
Fedu          0
Mjob          0
Fjob          0
reason        0
guardian      0
traveltime    0
studytime     0
failures      0
schoolsup     0
famsup        0
paid          0
activities    0
nursery       0
higher        0
internet      0
romantic      0
famrel        0
freetime      0
goout         0
Dalc          0
Walc          0
health        0
absences      0
passed        0
dtype: int64

In [46]:
df_csv.describe()

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,Walc,health,absences
count,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000
mean,16.696203,2.749367,2.521519,1.448101,2.035443,0.334177,3.944304,3.235443,3.108861,1.481013,2.291139,3.554430,5.708861
std,1.276043,1.094735,1.088201,0.697505,0.839240,0.743651,0.896659,0.998862,1.113278,0.890741,1.287897,1.390303,8.003096
min,15.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000
25%,16.000000,2.000000,2.000000,1.000000,1.000000,0.000000,4.000000,3.000000,2.000000,1.000000,1.000000,3.000000,0.000000
50%,17.000000,3.000000,2.000000,1.000000,2.000000,0.000000,4.000000,3.000000,3.000000,1.000000,2.000000,4.000000,4.000000
75%,18.000000,4.000000,3.000000,2.000000,2.000000,0.000000,5.000000,4.000000,4.000000,2.000000,3.000000,5.000000,8.000000
max,22.000000,4.000000,4.000000,4.000000,4.000000,3.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,75.000000

In [48]:
df_csv.sort_values(by = "age").head(18)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,passed
21,GP,M,15,U,GT3,T,4,4,health,health,...,yes,no,5,4,2,1,1,5,0,yes
20,GP,M,15,U,GT3,T,4,3,teacher,other,...,yes,no,4,4,1,1,1,1,0,yes
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,yes,no,4,3,2,2,3,3,10,yes
3,GP,F,15,U,GT3,T,4,2,health,services,...,yes,yes,3,2,2,1,1,5,2,yes
36,GP,M,15,U,LE3,T,4,3,teacher,services,...,yes,no,5,4,3,1,1,4,2,yes
38,GP,F,15,R,GT3,T,3,4,services,health,...,yes,no,4,3,2,1,1,5,2,yes
39,GP,F,15,R,GT3,T,2,2,at_home,other,...,no,no,4,3,1,1,1,2,8,yes
41,GP,M,15,U,LE3,T,4,4,teacher,other,...,yes,yes,5,4,3,2,4,5,8,yes
42,GP,M,15,U,GT3,T,4,4,services,teacher,...,yes,no,4,3,3,1,1,5,2,yes
43,GP,M,15,U,GT3,T,2,2,services,services,...,yes,no,5,4,1,1,1,1,0,yes
45,GP,F,15,U,LE3,A,4,3,other,other,...,yes,yes,5,2,2,1,1,5,8,no
48,GP,M,15,U,GT3,T,4,2,teacher,other,...,no,no,4,3,3,2,2,5,2,yes
49,GP,F,15,U,GT3,T,4,4,services,teacher,...,yes,no,4,4,4,1,1,3,2,no
51,GP,F,15,U,LE3,T,4,2,health,other,...,yes,no,4,3,3,1,1,5,2,yes
145,GP,F,15,U,GT3,T,1,1,other,services,...,yes,no,4,4,2,1,2,5,0,yes
146,GP,F,15,U,GT3,T,3,2,health,services,...,yes,no,3,3,2,1,1,3,0,no
147,GP,F,15,U,GT3,T,1,2,at_home,other,...,yes,no,4,3,2,1,1,5,2,yes
149,GP,M,15,U,LE3,A,2,1,services,other,...,yes,no,4,5,5,2,5,5,0,yes

In [51]:
df_csv.sort_values(by = "age",ascending=False).head(20)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,passed
247,GP,M,22,U,GT3,T,3,1,services,services,...,yes,yes,5,4,5,5,5,1,16,no
392,MS,M,21,R,GT3,T,1,1,other,other,...,no,no,5,5,3,3,3,3,3,no
390,MS,M,20,U,LE3,A,2,2,services,services,...,no,no,5,5,4,4,5,4,11,no
376,MS,F,20,U,GT3,T,4,2,health,other,...,yes,yes,5,4,3,1,1,3,4,yes
306,GP,M,20,U,GT3,A,3,2,services,other,...,no,no,5,5,3,1,1,5,0,yes
314,GP,F,19,U,GT3,T,1,1,at_home,health,...,yes,yes,4,1,2,1,1,3,14,yes
308,GP,M,19,R,GT3,T,3,3,other,services,...,no,yes,4,5,3,1,2,5,0,yes
370,MS,F,19,U,LE3,T,3,2,services,services,...,no,yes,3,2,2,1,1,3,4,no
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,yes,no,3,2,3,3,3,5,5,no
336,GP,F,19,R,GT3,A,3,1,services,at_home,...,no,no,5,4,3,1,2,5,12,yes
313,GP,F,19,U,LE3,T,3,2,services,other,...,yes,yes,4,2,2,1,2,1,22,yes
304,GP,M,19,U,GT3,T,3,3,other,other,...,yes,yes,4,4,4,1,1,3,20,yes
309,GP,F,19,U,LE3,T,1,1,at_home,other,...,yes,no,4,4,3,1,3,3,18,yes
353,MS,M,19,R,GT3,T,1,1,other,other,...,yes,no,4,4,4,3,3,5,4,no
340,GP,F,19,U,GT3,T,2,1,services,services,...,yes,yes,4,3,4,1,3,3,4,yes
307,GP,M,19,U,GT3,T,4,4,teacher,services,...,yes,yes,4,3,4,1,1,4,38,no
312,GP,M,19,U,GT3,T,1,2,other,services,...,yes,no,4,5,2,2,2,4,3,yes
315,GP,F,19,R,GT3,T,2,3,other,other,...,yes,yes,4,1,2,1,1,3,40,yes
311,GP,F,19,U,GT3,T,2,1,at_home,other,...,yes,yes,3,4,1,1,1,2,20,yes
210,GP,F,19,U,GT3,T,3,3,other,other,...,yes,no,4,3,3,1,2,3,10,no

In [55]:
df_csv.shape[0]

395

In [56]:
df_csv.shape[1]

31

In [57]:
df_csv.loc[14,['sex']]

sex    M
Name: 14, dtype: object

In [58]:
df_csv

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,passed
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,no,no,4,3,4,1,1,3,6,no
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,yes,no,5,3,3,1,1,3,4,no
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,yes,no,4,3,2,2,3,3,10,yes
3,GP,F,15,U,GT3,T,4,2,health,services,...,yes,yes,3,2,2,1,1,5,2,yes
4,GP,F,16,U,GT3,T,3,3,other,other,...,no,no,4,3,2,1,2,5,4,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,services,services,...,no,no,5,5,4,4,5,4,11,no
391,MS,M,17,U,LE3,T,3,1,services,services,...,yes,no,2,4,5,3,4,2,3,yes
392,MS,M,21,R,GT3,T,1,1,other,other,...,no,no,5,5,3,3,3,3,3,no
393,MS,M,18,R,LE3,T,3,2,services,other,...,yes,no,4,4,1,3,4,5,0,yes
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,yes,no,3,2,3,3,3,5,5,no