pip install pandas

In [1]:
import pandas as pd
import numpy as np

**Series**

In [4]:
s1 = pd.Series([24,1,5,66,88,99])
s1

0    24
1     1
2     5
3    66
4    88
5    99
dtype: int64

In [6]:
s2 = pd.Series([24,1,5,66,88,99],index = {'pavan','gopi','hulk','gouse','sam','ram'})
s2

pavan    24
ram       1
hulk      5
sam      66
gopi     88
gouse    99
dtype: int64

In [7]:
s1

0    24
1     1
2     5
3    66
4    88
5    99
dtype: int64

In [12]:
s3 = pd.Series([24,1,5,66,88,99],index={'pavan','gopi','hulk','gouse','sam','ram'},dtype = float)
s2

pavan    24.0
ram       1.0
hulk      5.0
sam      66.0
gopi     88.0
gouse    99.0
dtype: float64

In [14]:
s3['pavan']

np.float64(24.0)

In [15]:
s3[0]

/tmp/ipython-input-397937684.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s3[0]

np.float64(24.0)

In [18]:
s3["hulk"]

np.float64(5.0)

In [19]:
students = pd.Series(['pavan','gopi','hulk','gouse','sam','ram'],index = ["I","II","III","IV","V","VI"])
students

I      pavan
II      gopi
III     hulk
IV     gouse
V        sam
VI       ram
dtype: object

In [23]:
students["I"]

'pavan'

In [24]:
students["VI"]

'ram'

In [28]:
students[3]

/tmp/ipython-input-1158474101.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  students[3]

'gouse'

Creation of series using Dictionary

In [29]:
s4 = pd.Series({'a': 1, 'v' : 2, 'c': 3,'d' : 4})
s4

a    1
v    2
c    3
d    4
dtype: int64

**Dataframe**

In [53]:
s1 = pd.DataFrame([24,1,5,66,88,99])
s1

    0
0  24
1   1
2   5
3  66
4  88
5  99

In [38]:
d2 = pd.DataFrame([10,20,30],[40,50,60])
d2

     0
40  10
50  20
60  30

In [40]:
d2 = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]])
d2

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [41]:
students

I      pavan
II      gopi
III     hulk
IV     gouse
V        sam
VI       ram
dtype: object

In [42]:
# convert to series to DataFrame
d2 = pd.DataFrame(students)
d2

         0
I    pavan
II    gopi
III   hulk
IV   gouse
V      sam
VI     ram

In [43]:
d3 = pd.DataFrame([[70,80,90],[40,50,60],[10,20,30]],columns = ["maths","phy","chemstry"],index = ["pavan","gopi","Hulk"])
d3

       maths  phy  chemstry
pavan     70   80        90
gopi      40   50        60
Hulk      10   20        30

In [60]:

d2
#students

         0
I    pavan
II    gopi
III   hulk
IV   gouse
V      sam
VI     ram

In [69]:
dictionary = [{'pa1':1,'gop':2,'bro':4},{'pa1':55,'bro':45,'didi':00}]
dictionary

[{'pa1': 1, 'gop': 2, 'bro': 4}, {'pa1': 55, 'bro': 45, 'didi': 0}]

In [71]:
dictionary = [{'pa1':1,'gop':2,'bro':4},{'pa1':55,'bro':45,'didi':00}]
pd.DataFrame(dictionary,index = ['x','y'],dtype = float)

    pa1  gop   bro  didi
x   1.0  2.0   4.0   NaN
y  55.0  NaN  45.0   0.0

In [72]:
dictionary = [{'pa1':1,'gop':2,'bro':4},{'pa1':55,'bro':45,'didi':00}]
pd.DataFrame(dictionary,index = ['x','y'],dtype = int)

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer

**DataFrame operations**

In [122]:
marks = pd.DataFrame([[70,80,90],[40,50,60],[10,20,30]],columns = ["maths","phy","chemstry"],index = ["pavan","gopi","Hulk"])
marks

       maths  phy  chemstry
pavan     70   80        90
gopi      40   50        60
Hulk      10   20        30

In [114]:
marks['chemstry']

pavan    90
gopi     60
Hulk     30
Name: chemstry, dtype: int64

In [100]:
marks['phy']

pavan    80
gopi     50
Hulk     20
Name: phy, dtype: int64

In [115]:
marks['maths']['pavan']

np.int64(70)

In [81]:
marks['maths']['gopi']

np.int64(40)

In [123]:
marks['Total'] = marks['maths']+marks['phy']+marks['chemstry']
marks

       maths  phy  chemstry  Total
pavan     70   80        90    240
gopi      40   50        60    150
Hulk      10   20        30     60

In [124]:
marks["percantage"] = (marks['Total']/300)*100
marks

       maths  phy  chemstry  Total  percantage
pavan     70   80        90    240        80.0
gopi      40   50        60    150        50.0
Hulk      10   20        30     60        20.0

In [125]:
marks.percantage

pavan    80.0
gopi     50.0
Hulk     20.0
Name: percantage, dtype: float64

In [89]:
marks.Total

pavan    240
gopi     150
Hulk      60
Name: Total, dtype: int64

In [107]:
pop = marks.pop('phy')
pop

pavan    80
gopi     50
Hulk     20
Name: phy, dtype: int64

In [126]:
marks

       maths  phy  chemstry  Total  percantage
pavan     70   80        90    240        80.0
gopi      40   50        60    150        50.0
Hulk      10   20        30     60        20.0

In [127]:
marks.insert(3,"Qc",[99,97,95])
marks

       maths  phy  chemstry  Qc  Total  percantage
pavan     70   80        90  99    240        80.0
gopi      40   50        60  97    150        50.0
Hulk      10   20        30  95     60        20.0

In [130]:
d4 = pd.DataFrame({'ram':np.random.randint(1,10,size = (30)),'pa1':np.random.randint(2,10,size = (30)),'Hulk':np.random.randint(3,10,size = (30))})
d4

    ram  pa1  Hulk
0     2    4     7
1     4    8     3
2     8    9     9
3     7    8     4
4     1    5     5
5     9    9     3
6     4    9     7
7     3    2     5
8     1    6     6
9     6    2     3
10    5    5     7
11    8    6     5
12    5    9     4
13    8    4     3
14    4    2     6
15    4    8     7
16    4    9     4
17    5    8     3
18    6    8     6
19    2    3     7
20    5    6     6
21    7    6     5
22    9    4     6
23    6    7     5
24    4    2     9
25    8    8     5
26    4    3     5
27    8    7     3
28    3    4     5
29    9    5     5

In [131]:
d4.head()

   ram  pa1  Hulk
0    2    4     7
1    4    8     3
2    8    9     9
3    7    8     4
4    1    5     5

In [132]:
d4.head(10)

   ram  pa1  Hulk
0    2    4     7
1    4    8     3
2    8    9     9
3    7    8     4
4    1    5     5
5    9    9     3
6    4    9     7
7    3    2     5
8    1    6     6
9    6    2     3

In [133]:
d4.tail()

    ram  pa1  Hulk
25    8    8     5
26    4    3     5
27    8    7     3
28    3    4     5
29    9    5     5

In [135]:
d4.tail(5)

    ram  pa1  Hulk
25    8    8     5
26    4    3     5
27    8    7     3
28    3    4     5
29    9    5     5

In [142]:
d4.loc[10,"pa1"]

np.int64(5)

In [144]:
d4.loc[11,"ram"]

np.int64(8)

In [145]:
d4.loc[10:19,'pa1']

10    5
11    6
12    9
13    4
14    2
15    8
16    9
17    8
18    8
19    3
Name: pa1, dtype: int64

In [149]:
d4.loc[16:9,"pa1"]

Series([], Name: pa1, dtype: int64)

In [150]:
d4.loc[10:16,["pa1","ram"]]

    pa1  ram
10    5    5
11    6    8
12    9    5
13    4    8
14    2    4
15    8    4
16    9    4

In [152]:
d4.loc[10:16,["Hulk","ram"]]

    Hulk  ram
10     7    5
11     5    8
12     4    5
13     3    8
14     6    4
15     7    4
16     4    4

In [153]:
d4.tail(10)

    ram  pa1  Hulk
20    5    6     6
21    7    6     5
22    9    4     6
23    6    7     5
24    4    2     9
25    8    8     5
26    4    3     5
27    8    7     3
28    3    4     5
29    9    5     5

In [155]:
d4.iloc[4,1]  # index = 4 and coluhms = 1 as 2nd columns

np.int64(5)

In [156]:
d4.iloc[4:9,[0,2]]

   ram  Hulk
4    1     5
5    9     3
6    4     7
7    3     5
8    1     6

In [159]:
d4.iloc[[1,5,6,9,8,7,4,5,6,4,2,3,3,3]]

   ram  pa1  Hulk
1    4    8     3
5    9    9     3
6    4    9     7
9    6    2     3
8    1    6     6
7    3    2     5
4    1    5     5
5    9    9     3
6    4    9     7
4    1    5     5
2    8    9     9
3    7    8     4
3    7    8     4
3    7    8     4

In [160]:
d4.pa1

0     4
1     8
2     9
3     8
4     5
5     9
6     9
7     2
8     6
9     2
10    5
11    6
12    9
13    4
14    2
15    8
16    9
17    8
18    8
19    3
20    6
21    6
22    4
23    7
24    2
25    8
26    3
27    7
28    4
29    5
Name: pa1, dtype: int64

In [161]:
d4["pa1"]

0     4
1     8
2     9
3     8
4     5
5     9
6     9
7     2
8     6
9     2
10    5
11    6
12    9
13    4
14    2
15    8
16    9
17    8
18    8
19    3
20    6
21    6
22    4
23    7
24    2
25    8
26    3
27    7
28    4
29    5
Name: pa1, dtype: int64

In [169]:
d4["Total"] = d4["pa1"]+ d4["Hulk"]+ d4["ram"]
d4

    ram  pa1  Hulk  Total
0     2    4     7     13
1     4    8     3     15
2     8    9     9     26
3     7    8     4     19
4     1    5     5     11
5     9    9     3     21
6     4    9     7     20
7     3    2     5     10
8     1    6     6     13
9     6    2     3     11
10    5    5     7     17
11    8    6     5     19
12    5    9     4     18
13    8    4     3     15
14    4    2     6     12
15    4    8     7     19
16    4    9     4     17
17    5    8     3     16
18    6    8     6     20
19    2    3     7     12
20    5    6     6     17
21    7    6     5     18
22    9    4     6     19
23    6    7     5     18
24    4    2     9     15
25    8    8     5     21
26    4    3     5     12
27    8    7     3     18
28    3    4     5     12
29    9    5     5     19

In [ ]:
employees = [['rk', 100, 19000], ['js', 101, 22000], ['am', 102, 18500], ['pt', 103, 25000], ['ks', 104, 21000], ['rv', 105, 20000], ['sl', 106, 23000], ['mj', 107, 19500], ['dp', 108, 24000], ['cl', 109, 20500]]
employees